-- Sample data for Citizen Proposals, County Proposed Projects, and Project Announcements
-- This file contains demo data for testing purposes

-- Insert Citizen Proposals
INSERT INTO `citizen_proposals` (`title`, `description`, `category`, `location`, `estimated_cost`, `proposer_name`, `proposer_email`, `proposer_phone`, `proposer_address`, `justification`, `expected_benefits`, `timeline`, `status`, `submission_date`) VALUES
('Construction of Modern Market in Kondele', 'Proposal for a modern market facility to serve the growing population in Kondele area', 'Infrastructure', 'Kondele Ward', 15000000.00, 'John Mwangi', 'john.mwangi@email.com', '+254712345678', 'Kondele, Kisumu', 'The current market is overcrowded and lacks proper facilities', 'Improved trading environment, increased revenue, better hygiene', '12 months', 'Under Review', '2024-01-15 10:00:00'),
('Youth Skills Training Center', 'Establishment of a vocational training center for youth empowerment', 'Education', 'Kisumu Central', 25000000.00, 'Sarah Akinyi', 'sarah.akinyi@email.com', '+254723456789', 'Kisumu Central, Kisumu', 'High unemployment rate among youth in the area', 'Youth employment, skill development, economic growth', '18 months', 'Approved', '2024-01-10 14:30:00'),
('Water Supply Project for Rural Areas', 'Extension of clean water supply to underserved rural communities', 'Water & Sanitation', 'Nyakach Sub-County', 35000000.00, 'Peter Ochieng', 'peter.ochieng@email.com', '+254734567890', 'Nyakach, Kisumu', 'Communities lack access to clean water', 'Improved health, reduced waterborne diseases', '24 months', 'Rejected', '2024-01-05 09:15:00'),
('Community Health Center Upgrade', 'Upgrade of existing health center with modern equipment and facilities', 'Health', 'Muhoroni Ward', 20000000.00, 'Grace Achieng', 'grace.achieng@email.com', '+254745678901', 'Muhoroni, Kisumu', 'Current facility is outdated and lacks essential equipment', 'Better healthcare access, improved patient outcomes', '15 months', 'Under Review', '2024-02-01 11:00:00'),
('Agricultural Training and Support Program', 'Comprehensive training program for farmers on modern agricultural practices', 'Agriculture', 'Nyando Sub-County', 18000000.00, 'James Otieno', 'james.otieno@email.com', '+254756789012', 'Nyando, Kisumu', 'Farmers need training on modern farming techniques', 'Increased crop yields, improved food security', '12 months', 'Approved', '2024-01-20 16:45:00');

-- Insert County Proposed Projects
INSERT INTO `county_proposed_projects` (`title`, `description`, `category`, `location`, `estimated_cost`, `justification`, `expected_benefits`, `timeline`, `status`, `priority`, `department`, `project_manager`, `contact`, `start_date`, `end_date`, `progress`, `budget_allocated`, `budget_utilized`, `stakeholders`, `risks`) VALUES
('Kisumu Lakefront Development Phase II', 'Development of the second phase of the Kisumu Lakefront including modern recreational facilities, walkways, and commercial spaces.', 'Infrastructure', 'Kisumu Central', 250000000.00, 'To enhance tourism, create employment opportunities, and improve the city\'s aesthetic appeal.', 'Increased tourism revenue, job creation, improved city image, enhanced recreational facilities.', '18 months', 'Planning', 'High', 'Department of Physical Planning', 'Dr. Sarah Wanjiku', 'planning@kisumu.go.ke', '2024-12-01', '2026-05-31', 15.00, 50000000.00, 7500000.00, 'County Assembly, Tourism Board, Environmental Authority', 'Environmental impact, Community displacement, Budget constraints'),
('Smart City Digital Infrastructure', 'Implementation of smart city technologies including IoT sensors, digital payment systems, and e-governance platforms.', 'Technology', 'Kisumu County', 180000000.00, 'To modernize service delivery, improve efficiency, and enhance citizen engagement.', 'Improved service delivery, reduced corruption, enhanced transparency, better data-driven decisions.', '24 months', 'Approved', 'High', 'ICT Department', 'Eng. Michael Ochieng', 'ict@kisumu.go.ke', '2024-11-01', '2026-10-31', 25.00, 45000000.00, 11250000.00, 'National ICT Authority, Telecom Companies, Software Vendors', 'Technology obsolescence, Cybersecurity threats, User adoption'),
('Agricultural Value Chain Development', 'Comprehensive agricultural development program focusing on value addition, market linkages, and farmer capacity building.', 'Agriculture', 'Nyando, Muhoroni, Nyakach', 120000000.00, 'To boost agricultural productivity, reduce post-harvest losses, and increase farmer incomes.', 'Increased farmer incomes, reduced food waste, improved food security, job creation.', '36 months', 'Implementation', 'Medium', 'Department of Agriculture', 'Dr. Grace Akinyi', 'agriculture@kisumu.go.ke', '2024-08-01', '2027-07-31', 40.00, 30000000.00, 12000000.00, 'Farmers Cooperatives, Agricultural Research Institute, Export Companies', 'Climate change, Market volatility, Farmer adoption'),
('Universal Healthcare Access Program', 'Expansion of healthcare services to ensure universal access to quality healthcare across all wards.', 'Health', 'All Wards', 200000000.00, 'To improve health outcomes, reduce maternal and child mortality, and ensure healthcare equity.', 'Improved health outcomes, reduced mortality rates, better healthcare access, enhanced quality of life.', '30 months', 'Planning', 'High', 'Department of Health', 'Dr. Peter Mwangi', 'health@kisumu.go.ke', '2025-01-01', '2027-06-30', 10.00, 50000000.00, 5000000.00, 'Ministry of Health, WHO, Medical Practitioners', 'Resource constraints, Staff shortages, Infrastructure challenges'),
('Youth Skills Development Centers', 'Establishment of modern skills development centers to equip youth with market-relevant technical skills.', 'Education', 'Kisumu Central, Nyando, Muhoroni', 150000000.00, 'To address youth unemployment, equip youth with marketable skills, and promote entrepreneurship.', 'Reduced youth unemployment, increased entrepreneurship, improved economic productivity, social stability.', '24 months', 'Approved', 'Medium', 'Department of Youth Affairs', 'Ms. Jane Adhiambo', 'youth@kisumu.go.ke', '2024-12-01', '2026-11-30', 20.00, 37500000.00, 7500000.00, 'TVET Authority, Private Sector, Youth Groups', 'Low enrollment, Equipment maintenance, Industry relevance'),
('Water and Sanitation Improvement', 'Comprehensive water and sanitation improvement program including borehole drilling, water treatment, and sanitation facilities.', 'Water & Sanitation', 'Rural Wards', 100000000.00, 'To improve access to clean water, reduce waterborne diseases, and enhance sanitation standards.', 'Improved water access, reduced diseases, better sanitation, enhanced quality of life.', '18 months', 'Implementation', 'High', 'Department of Water', 'Eng. Susan Owino', 'water@kisumu.go.ke', '2024-09-01', '2026-02-28', 35.00, 25000000.00, 8750000.00, 'KIWASCO, Water Resources Authority, Community Groups', 'Groundwater depletion, Maintenance challenges, Community participation');

-- Insert milestones for County Proposed Projects
INSERT INTO `county_proposed_project_milestones` (`project_id`, `name`, `description`, `target_date`, `completed`, `completed_date`, `sequence_order`) VALUES
-- Project 1 milestones
(1, 'Environmental Impact Assessment', 'Complete EIA for lakefront development', '2024-10-15', 1, '2024-10-15', 1),
(1, 'Community Consultation', 'Hold public participation meetings', '2024-11-01', 1, '2024-11-01', 2),
(1, 'Design Finalization', 'Finalize architectural and engineering designs', '2024-12-15', 0, NULL, 3),
(1, 'Tender Award', 'Award construction contract', '2025-02-01', 0, NULL, 4),
(1, 'Construction Start', 'Begin construction work', '2025-03-01', 0, NULL, 5),
-- Project 2 milestones
(2, 'Feasibility Study', 'Complete feasibility study for smart city infrastructure', '2024-09-30', 1, '2024-09-30', 1),
(2, 'Vendor Selection', 'Select technology vendors', '2024-10-31', 1, '2024-10-31', 2),
(2, 'Pilot Implementation', 'Deploy pilot system in selected areas', '2025-01-31', 0, NULL, 3),
(2, 'Full Deployment', 'Roll out system county-wide', '2025-06-30', 0, NULL, 4),
(2, 'Training & Support', 'Train staff and provide ongoing support', '2025-12-31', 0, NULL, 5),
-- Project 3 milestones
(3, 'Farmer Registration', 'Register participating farmers', '2024-08-31', 1, '2024-08-31', 1),
(3, 'Training Programs', 'Conduct farmer training sessions', '2024-10-31', 1, '2024-10-31', 2),
(3, 'Equipment Distribution', 'Distribute farming equipment to farmers', '2025-01-31', 0, NULL, 3),
(3, 'Market Linkages', 'Establish market connections for farmers', '2025-06-30', 0, NULL, 4),
(3, 'Value Addition Centers', 'Set up value addition facilities', '2026-03-31', 0, NULL, 5),
-- Project 4 milestones
(4, 'Needs Assessment', 'Assess healthcare needs across all wards', '2024-11-30', 1, '2024-11-30', 1),
(4, 'Facility Mapping', 'Map existing healthcare facilities', '2025-01-31', 0, NULL, 2),
(4, 'Staff Recruitment', 'Recruit additional healthcare staff', '2025-03-31', 0, NULL, 3),
(4, 'Equipment Procurement', 'Procure medical equipment', '2025-06-30', 0, NULL, 4),
(4, 'Service Launch', 'Launch expanded healthcare services', '2025-09-30', 0, NULL, 5),
-- Project 5 milestones
(5, 'Site Selection', 'Select locations for skills centers', '2024-10-31', 1, '2024-10-31', 1),
(5, 'Curriculum Development', 'Develop training curricula', '2024-11-30', 1, '2024-11-30', 2),
(5, 'Facility Construction', 'Construct skills development centers', '2025-06-30', 0, NULL, 3),
(5, 'Equipment Installation', 'Install training equipment', '2025-08-31', 0, NULL, 4),
(5, 'Training Commencement', 'Begin training programs', '2025-10-01', 0, NULL, 5),
-- Project 6 milestones
(6, 'Site Survey', 'Survey sites for water projects', '2024-09-30', 1, '2024-09-30', 1),
(6, 'Borehole Drilling', 'Drill boreholes in selected locations', '2024-11-30', 1, '2024-11-30', 2),
(6, 'Water Treatment Plants', 'Construct water treatment facilities', '2025-03-31', 0, NULL, 3),
(6, 'Distribution Networks', 'Install water distribution networks', '2025-08-31', 0, NULL, 4),
(6, 'Sanitation Facilities', 'Construct sanitation facilities', '2025-12-31', 0, NULL, 5);

-- Insert Project Announcements
INSERT INTO `project_announcements` (`title`, `description`, `content`, `category`, `type`, `date`, `time`, `location`, `organizer`, `status`, `priority`, `image_url`, `attendees`, `max_attendees`) VALUES
('Public Participation Meeting - Kondele Market Project', 'Join us for a public participation meeting to discuss the proposed Kondele Market development project. Your input is valuable!', 'The County Government of Kisumu invites all residents to participate in a public meeting regarding the proposed Kondele Market development project. This meeting will provide an opportunity for community members to:\n\n• Learn about the project details and timeline\n• Ask questions and provide feedback\n• Share concerns and suggestions\n• Understand the project\'s impact on the community\n\nDate: March 15, 2024\nTime: 2:00 PM - 5:00 PM\nVenue: Kondele Community Hall\n\nAll interested parties are encouraged to attend.', 'Public Participation', 'Meeting', '2024-03-15', '14:00:00', 'Kondele Community Hall', 'County Planning Department', 'Upcoming', 'High', NULL, 45, 100),
('Project Launch - Youth Skills Training Center', 'Official launch of the new Youth Skills Training Center in Kisumu Central. Join us for the grand opening ceremony!', 'We are excited to announce the official launch of the Youth Skills Training Center, a state-of-the-art facility designed to empower young people with practical skills for employment and entrepreneurship.\n\nProgram Highlights:\n• Vocational training in various trades\n• Entrepreneurship development\n• Job placement assistance\n• Mentorship programs\n\nLaunch Event Details:\nDate: March 20, 2024\nTime: 10:00 AM - 2:00 PM\nVenue: Youth Skills Training Center, Kisumu Central\n\nSpecial guests include the Governor, County officials, and successful alumni.', 'Project Launch', 'Event', '2024-03-20', '10:00:00', 'Youth Skills Training Center, Kisumu Central', 'Youth Development Department', 'Upcoming', 'High', NULL, 120, 200),
('Water Project Update - Nyakach Sub-County', 'Progress update on the water supply extension project in Nyakach Sub-County. Phase 1 completed successfully.', 'We are pleased to announce the successful completion of Phase 1 of the water supply extension project in Nyakach Sub-County.\n\nCompleted Work:\n• Installation of 15km of water pipes\n• Construction of 3 water storage tanks\n• Connection of 500 households\n• Establishment of 5 water kiosks\n\nNext Steps:\n• Phase 2 will begin in April 2024\n• Additional 20km of pipes to be installed\n• 800 more households to be connected\n• Project completion expected by December 2024\n\nFor more information, contact the Water Department.', 'Project Update', 'Update', '2024-03-10', '09:00:00', 'Nyakach Sub-County', 'Water & Sanitation Department', 'Completed', 'Medium', NULL, 0, 0),
('Call for Proposals - Agricultural Development Projects', 'The County Government is seeking proposals for agricultural development projects. Submit your innovative ideas!', 'The County Government of Kisumu is calling for proposals for innovative agricultural development projects that will benefit local farmers and communities.\n\nEligibility Criteria:\n• Registered farmer groups or cooperatives\n• Agricultural organizations\n• Community-based organizations\n• Individual farmers with innovative ideas\n\nProject Focus Areas:\n• Modern farming techniques\n• Irrigation systems\n• Post-harvest handling\n• Market access improvement\n• Value addition\n\nSubmission Deadline: April 30, 2024\nMaximum Funding: KES 2,000,000 per project\n\nFor application forms and guidelines, visit the Agriculture Department offices.', 'Call for Proposals', 'Opportunity', '2024-04-30', '17:00:00', 'Agriculture Department Offices', 'Agriculture Department', 'Open', 'High', NULL, 0, 0),
('Health Center Renovation - Temporary Closure Notice', 'Kisumu Central Health Center will be temporarily closed for renovation works. Alternative arrangements provided.', 'Please be informed that Kisumu Central Health Center will be temporarily closed for renovation works from March 25 to April 15, 2024.\n\nRenovation Works:\n• Upgrading of patient rooms\n• Installation of new medical equipment\n• Improvement of sanitation facilities\n• Expansion of waiting areas\n\nAlternative Health Services:\n• Jaramogi Oginga Odinga Teaching and Referral Hospital\n• Kisumu County Hospital\n• Private health facilities in the area\n\nEmergency services will be available at the nearest alternative facility.\n\nWe apologize for any inconvenience caused.', 'Service Notice', 'Notice', '2024-03-25', '08:00:00', 'Kisumu Central Health Center', 'Health Department', 'Active', 'High', NULL, 0, 0),
('Smart City Initiative Launch', 'Official launch of the Smart City Digital Infrastructure project. Join us to learn about the future of digital services in Kisumu.', 'The County Government is excited to launch the Smart City Digital Infrastructure project, which will transform service delivery through technology.\n\nKey Features:\n• Digital payment systems\n• IoT sensors for monitoring\n• E-governance platforms\n• Citizen engagement tools\n\nLaunch Event:\nDate: May 1, 2024\nTime: 9:00 AM - 1:00 PM\nVenue: Kisumu County Hall\n\nAll stakeholders and citizens are welcome to attend.', 'Project Launch', 'Event', '2024-05-01', '09:00:00', 'Kisumu County Hall', 'ICT Department', 'Upcoming', 'High', NULL, 85, 150),
('Emergency Water Rationing Notice', 'Due to maintenance works, water supply will be rationed in selected areas. Please store water in advance.', 'The Water Department wishes to inform residents that scheduled maintenance works will require water rationing in the following areas:\n\nAffected Areas:\n• Kondele Ward\n• Nyalenda Ward\n• Manyatta Ward\n\nSchedule:\n• March 28, 2024: 6:00 AM - 12:00 PM\n• March 29, 2024: 6:00 AM - 12:00 PM\n\nResidents are advised to store water in advance. Water tankers will be available at designated points.\n\nFor inquiries, contact: 0712345678', 'Emergency', 'Notice', '2024-03-28', '06:00:00', 'Kondele, Nyalenda, Manyatta Wards', 'Water Department', 'Active', 'High', NULL, 0, 0);

