#!/usr/bin/env bash
#
# One-time bootstrap for the KEMRI database on the server's native PostgreSQL.
# Run this ON THE SERVER as the SSH user (no sudo needed — gov_local_user
# already has CREATEDB, the same way Machakos uses it). Idempotent.
#
# What it does:
#   1. Verifies the existing role gov_local_user (created when Machakos was
#      installed) can authenticate on 127.0.0.1:${DB_PORT}.
#   2. Creates database `kemridb` owned by gov_local_user (if missing).
#   3. Enables pg_trgm, unaccent, and pgvector inside kemridb.
#   4. Bootstraps ~/dev/kemri/api/.env from a template if missing (DB_*, a
#      freshly generated JWT_SECRET, SMTP placeholders).
#   5. Prints a connection check.
#
# After this runs, push the local kemridb from your laptop:
#   DEPLOY_SYNC_DB=1 DEPLOY_SYNC_DB_CONFIRM=yes ./deploy/deploy-kemri-pathways.sh
#
# Override variables (defaults match Machakos on this server):
#   DB_NAME=kemridb DB_USER=gov_local_user DB_PASSWORD='Admin2020@#' \
#   DB_PORT=5433 ./deploy/setup-kemridb-on-server.sh
#
set -euo pipefail

DB_NAME="${DB_NAME:-kemridb}"
DB_USER="${DB_USER:-gov_local_user}"
DB_PASSWORD="${DB_PASSWORD:-Admin2020@#}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5433}"

# Locate a psql client.
PSQL_BIN=""
for candidate in /usr/bin/psql /usr/local/bin/psql /usr/lib/postgresql/18/bin/psql \
                 /usr/lib/postgresql/17/bin/psql /usr/lib/postgresql/16/bin/psql \
                 /usr/lib/postgresql/15/bin/psql; do
  if [[ -x "$candidate" ]]; then PSQL_BIN="$candidate"; break; fi
done
if [[ -z "$PSQL_BIN" ]] && command -v psql >/dev/null 2>&1; then
  PSQL_BIN="$(command -v psql)"
fi
if [[ -z "$PSQL_BIN" ]]; then
  echo "ERROR: psql not found. Install postgresql-client first." >&2
  exit 1
fi

echo "==> Using psql: $PSQL_BIN   target: ${DB_USER}@${DB_HOST}:${DB_PORT}"

psql_app() { PGPASSWORD="$DB_PASSWORD" "$PSQL_BIN" -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -v ON_ERROR_STOP=1 "$@"; }

# 1. Connectivity --------------------------------------------------------------
if ! psql_app -d postgres -tAc "SELECT 1" >/dev/null 2>&1; then
  echo "ERROR: cannot connect as ${DB_USER}@${DB_HOST}:${DB_PORT}." >&2
  echo "  - Confirm the password (Machakos's api/.env uses the same one)." >&2
  echo "  - Confirm port (server uses 5433, not 5432)." >&2
  echo "  - Confirm pg_hba.conf allows host 127.0.0.1 md5 for ${DB_USER}." >&2
  exit 1
fi

# Sanity check on privileges (rolcreatedb is what we need).
ROLE_FLAGS=$(psql_app -d postgres -tAc \
  "SELECT rolsuper||','||rolcreatedb FROM pg_roles WHERE rolname='${DB_USER}'" || true)
case "$ROLE_FLAGS" in
  *,t) echo "==> ${DB_USER} has CREATEDB" ;;
  *)   echo "WARN: ${DB_USER} may lack CREATEDB (got: $ROLE_FLAGS). Continuing — DB may already exist." ;;
esac

# 2. Database -----------------------------------------------------------------
if psql_app -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -qx 1; then
  echo "==> Database ${DB_NAME} already exists — leaving it alone."
else
  echo "==> Creating database ${DB_NAME} owned by ${DB_USER}"
  psql_app -d postgres -c "CREATE DATABASE \"${DB_NAME}\" OWNER \"${DB_USER}\" ENCODING 'UTF8';"
fi

# 3. Extensions ---------------------------------------------------------------
echo "==> Ensuring extensions on ${DB_NAME}"
psql_app -d "${DB_NAME}" <<SQL
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
-- pgvector is available on this server; install only if present.
DO \$\$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'vector') THEN
    CREATE EXTENSION IF NOT EXISTS vector;
  ELSE
    RAISE NOTICE 'pgvector not available; install postgresql-16-pgvector to enable RAG / embeddings.';
  END IF;
END
\$\$;
SQL

# 4. Bootstrap api/.env -------------------------------------------------------
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_ENV="${ROOT}/api/.env"

if [[ -f "$API_ENV" ]]; then
  echo "==> api/.env already exists — leaving it alone."
else
  JWT_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '+/=\n' | cut -c1-64)"
  cat >"$API_ENV" <<ENV
# Server api/.env for KEMRI / KIMES (auto-generated by deploy/setup-kemridb-on-server.sh).
# Edit by hand if you need to override SMTP, JWT, or DB connection details.
DB_TYPE=postgresql
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USER=${DB_USER}
DB_PASSWORD="${DB_PASSWORD}"
DB_NAME=${DB_NAME}

JWT_SECRET=${JWT_SECRET}

# SMTP — fill in if you want user-onboarding / password-reset emails to work.
# (Copy values from your laptop's api/.env if you have a working KEMRI / ICS
# Kenya SMTP account.)
SMTP_HOST=mail.icskenya.co.ke
SMTP_PORT=465
SMTP_SECURE=true
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
APP_LOGIN_URL=https://kemri.pathwaystechnologies.com/login

VITE_CERT_COUNTY_NAME=KEMRI
ENV
  chmod 600 "$API_ENV"
  echo "==> Wrote ${API_ENV}  (mode 600). Fill in SMTP_* if you need password emails."
fi

# 5. Final connectivity check -------------------------------------------------
RESULT="$(psql_app -d "${DB_NAME}" -tAc "SELECT 'OK: ' || current_user || '@' || current_database();")"
echo
echo "==> ${RESULT}"
echo "    Next from your laptop:"
echo "      DEPLOY_SYNC_DB=1 DEPLOY_SYNC_DB_CONFIRM=yes ./deploy/deploy-kemri-pathways.sh"
