/**
 * KEMRI Board Quarterly Scorecard — KIMES v5 §8.3.
 *
 * The most senior dashboard in KIMES. Auto-generated by the AI Reporting
 * Engine from KIMES data, reviewed by the MEL Division Head, approved by the
 * Director General, and published to the Board Portal within 3 weeks of
 * quarter-end. It is a *composition* of existing widgets — RAG donut, KPI
 * tiles, escalation funnel, strategic-plan progress, compliance by centre,
 * SERU watchlist — laid out in the five sections defined in the v5 PDF:
 *
 *   1. KPIs at a glance
 *   2. Strategic Plan progress
 *   3. Compliance & Governance
 *   4. Items requiring Board attention
 *   5. Donor relationship summary
 *
 * The page is read-only and print-friendly so a Board Secretary can save
 * the rendered view as PDF for inclusion in the Board pack.
 */

import React, { useEffect, useMemo, useState } from 'react';
import { Link as RouterLink } from 'react-router-dom';
import {
    Alert, Box, Button, Card, CardContent, Chip, CircularProgress,
    Container, Divider, Grid, Paper, Stack, Tooltip, Typography,
} from '@mui/material';
import {
    Print as PrintIcon, Refresh as RefreshIcon,
    PolicyOutlined as PolicyIcon,
    GavelOutlined as GavelIcon,
    HealthAndSafety as KemriIcon,
    Insights as InsightsIcon,
    Warning as WarningIcon,
    AutoAwesome as OutputsIcon,
} from '@mui/icons-material';
import {
    ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis,
    ReferenceLine, Tooltip as RTooltip, CartesianGrid,
} from 'recharts';
import kemriService from '../api/kemriService';
import { ragMeta } from '../utils/kemriFormat';
import { ROUTES } from '../configs/appConfig';

const RAG_COLORS = {
    green:   ragMeta('green').hex,
    amber:   ragMeta('amber').hex,
    red:     ragMeta('red').hex,
    pending: ragMeta('pending').hex,
};

const fmtNum = (n) => Number(n || 0).toLocaleString();
const fmtPct = (n) => `${Math.round(Number(n || 0))}%`;
const fmtMoney = (n) => {
    const v = Number(n || 0);
    if (!Number.isFinite(v) || v === 0) return '—';
    if (v >= 1e9) return `${(v / 1e9).toFixed(2)}B`;
    if (v >= 1e6) return `${(v / 1e6).toFixed(2)}M`;
    if (v >= 1e3) return `${(v / 1e3).toFixed(1)}K`;
    return v.toLocaleString();
};

function SectionHeader({ icon, number, title, blurb }) {
    const Icon = icon;
    return (
        <Box sx={{ mb: 2 }}>
            <Stack direction="row" alignItems="center" spacing={1.5}>
                <Box sx={{
                    width: 42, height: 42, borderRadius: 1.5,
                    bgcolor: '#003e6b', color: 'white',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontWeight: 800, fontSize: 18,
                }}>
                    {Icon ? <Icon /> : number}
                </Box>
                <Box>
                    <Typography variant="overline" sx={{ color: 'text.secondary', letterSpacing: 1.5 }}>
                        Section {number}
                    </Typography>
                    <Typography variant="h5" sx={{ fontWeight: 800, lineHeight: 1.1 }}>
                        {title}
                    </Typography>
                    {blurb && (
                        <Typography variant="caption" color="text.secondary">{blurb}</Typography>
                    )}
                </Box>
            </Stack>
            <Divider sx={{ mt: 1.25 }} />
        </Box>
    );
}

function KpiBlock({ label, value, sub, color }) {
    return (
        <Paper variant="outlined" sx={{ p: 2, borderRadius: 2, height: '100%' }}>
            <Typography variant="overline" sx={{ color: 'text.secondary', letterSpacing: 1 }}>{label}</Typography>
            <Typography variant="h3" sx={{ fontWeight: 800, color: color || 'text.primary', mt: 0.5, lineHeight: 1 }}>
                {value}
            </Typography>
            {sub && <Typography variant="caption" color="text.secondary">{sub}</Typography>}
        </Paper>
    );
}

export default function KemriBoardScorecardPage() {
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [summary, setSummary] = useState(null);
    const [strategic, setStrategic] = useState(null);
    const [escSummary, setEscSummary] = useState(null);

    const refresh = async () => {
        setLoading(true); setError(null);
        try {
            const [s, sp, e] = await Promise.allSettled([
                kemriService.getDashboardSummary(),
                kemriService.getStrategicPlanProgress(),
                kemriService.getEscalationsSummary(),
            ]);
            setSummary(s.status === 'fulfilled' ? s.value : null);
            setStrategic(sp.status === 'fulfilled' ? sp.value : null);
            setEscSummary(e.status === 'fulfilled' ? e.value : null);
        } catch (err) {
            setError(err?.response?.data?.message || err.message || 'Failed to load scorecard');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { refresh(); }, []);

    // Derived data
    const rag = summary?.ragSummary || { green: 0, amber: 0, red: 0, pending: 0 };
    const ragData = [
        { name: 'Green',   value: rag.green   || 0, color: RAG_COLORS.green },
        { name: 'Amber',   value: rag.amber   || 0, color: RAG_COLORS.amber },
        { name: 'Red',     value: rag.red     || 0, color: RAG_COLORS.red },
        { name: 'Pending', value: rag.pending || 0, color: RAG_COLORS.pending },
    ];
    const ragTotal = ragData.reduce((a, b) => a + b.value, 0);
    const ragGreenPct = ragTotal ? Math.round((ragData[0].value / ragTotal) * 100) : 0;

    const portfolio = summary?.portfolio || {};
    const totalEsc = useMemo(() => {
        if (!escSummary) return 0;
        return Object.values(escSummary).reduce((a, b) => a + Number(b?.open || 0), 0);
    }, [escSummary]);

    const escalationFunnel = useMemo(() => {
        if (!escSummary) return [];
        const totalActive = Number(portfolio.activeProjects || portfolio.totalProjects || 0);
        const lvlOpen = (l) => Number(escSummary?.[l]?.open || 0);
        const totals = [lvlOpen(1), lvlOpen(2), lvlOpen(3), lvlOpen(4), lvlOpen(5)];
        const compliant = Math.max(0, totalActive - totals.reduce((a, b) => a + b, 0));
        return [
            { stage: 'Compliant & on track', n: compliant, color: '#16A34A' },
            { stage: 'L1 Minor',              n: totals[0], color: '#FBBF24' },
            { stage: 'L2 Moderate',           n: totals[1], color: '#F97316' },
            { stage: 'L3 Significant',        n: totals[2], color: '#DC2626' },
            { stage: 'L4 Severe (DG)',        n: totals[3], color: '#7F1D1D' },
            { stage: 'L5 Institutional',      n: totals[4], color: '#0F172A' },
        ];
    }, [escSummary, portfolio]);

    const fundingByCentre = useMemo(() => {
        const rows = summary?.byCentre || [];
        return rows.slice(0, 8).map((r) => ({
            centre: r.centreCode || r.centre || `#${r.centreId || ''}`,
            budget: Number(r.budgetTotal || 0),
            actual: Number(r.expenditure || 0),
            utilisation: r.budgetTotal ? Math.round((Number(r.expenditure || 0) / Number(r.budgetTotal)) * 100) : 0,
        }));
    }, [summary]);

    const outputsByType = summary?.outputsByType || [];

    const itemsForBoard = useMemo(() => {
        const items = [];
        if (escSummary) {
            const l5 = Number(escSummary[5]?.open || 0);
            const l4 = Number(escSummary[4]?.open || 0);
            if (l5 > 0) items.push({ severity: 'critical', text: `${l5} L5 institutional non-conformity case(s) open. Board directive required.` });
            if (l4 > 0) items.push({ severity: 'high',     text: `${l4} L4 severe non-conformity case(s) at DG intervention. DG-NCF-001 letter pipeline active.` });
        }
        const seruExp = (summary?.seruExpiring || []).filter((s) => Number(s.daysToExpiry || 0) <= 14);
        if (seruExp.length > 0) items.push({ severity: 'high',  text: `${seruExp.length} SERU approval(s) expire within 14 days. Ethics compliance at risk.` });
        const grayHairs = (summary?.byCentre || []).filter((c) => Number(c.red || 0) > 0);
        if (grayHairs.length > 0) {
            items.push({ severity: 'medium', text: `${grayHairs.length} centre(s) carry one or more Red-RAG projects. Centre Director remediation in progress.` });
        }
        if (items.length === 0) {
            items.push({ severity: 'info', text: 'No items require Board attention this quarter — institution is operating within agreed tolerances.' });
        }
        return items;
    }, [escSummary, summary]);

    const donorRelationship = useMemo(() => {
        const donors = (summary?.byDonor || []).slice(0, 6);
        return donors.map((d) => ({
            donor: d.donor || d.donorName || `Donor #${d.donorId || ''}`,
            studies: Number(d.studyCount || d.n || 0),
            funding: Number(d.fundingTotal || d.funding || 0),
        }));
    }, [summary]);

    const handlePrint = () => window.print();

    return (
        // `kimes-print-page` opts this entire container into the global
        // print stylesheet (src/index.css) so the tree sidebar, AppBar,
        // ribbon menu and other app chrome are stripped from the printed
        // scorecard.  Elements marked `kimes-noprint` (refresh / print
        // buttons, etc.) stay interactive on screen but vanish in print.
        <Container maxWidth="xl" className="kimes-print-page" sx={{ py: { xs: 2, md: 3 } }}>
            {/* Print header */}
            <Card elevation={0} sx={{
                mb: 3, borderRadius: 3, color: 'white',
                background: 'linear-gradient(135deg, #003e6b 0%, #005a9c 50%, #1976d2 100%)',
            }}>
                <CardContent sx={{ py: { xs: 2.5, md: 3 } }}>
                    <Stack direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} spacing={2}>
                        <Box sx={{
                            width: 56, height: 56, borderRadius: '50%',
                            bgcolor: 'rgba(255,255,255,0.18)',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                        }}>
                            <KemriIcon sx={{ fontSize: 28 }} />
                        </Box>
                        <Box sx={{ flex: 1 }}>
                            <Typography variant="overline" sx={{ opacity: 0.85, letterSpacing: 2 }}>
                                KEMRI / KIMES v5 — Board Portal
                            </Typography>
                            <Typography variant="h4" sx={{ fontWeight: 800 }}>
                                Board Quarterly Scorecard
                            </Typography>
                            <Typography variant="body2" sx={{ opacity: 0.92 }}>
                                Auto-generated by the KIMES AI Reporting Engine · reviewed by MEL Division Head · signed by Director General.
                                {strategic && (
                                    <> Current period: <strong>{strategic.fyLabel} {strategic.quarter}</strong>.</>
                                )}
                            </Typography>
                        </Box>
                        <Stack direction="row" spacing={1} className="kimes-noprint">
                            <Button startIcon={<RefreshIcon />} onClick={refresh} sx={{ color: 'white', borderColor: 'rgba(255,255,255,0.5)' }} variant="outlined">Refresh</Button>
                            <Button startIcon={<PrintIcon />} onClick={handlePrint} variant="contained" color="secondary">Print / Save as PDF</Button>
                        </Stack>
                    </Stack>
                </CardContent>
            </Card>

            {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
            {loading && (
                <Box sx={{ textAlign: 'center', py: 4 }}><CircularProgress /></Box>
            )}

            {!loading && (
                <>
                    {/* ============= SECTION 1: KPIs ============= */}
                    <SectionHeader number={1} title="KPIs at a glance" blurb="Institution-wide performance signals." />
                    <Grid container spacing={1.5} sx={{ mb: 4 }}>
                        <Grid item xs={6} md={3}>
                            <KpiBlock label="Active projects"      value={fmtNum(portfolio.activeProjects || portfolio.totalProjects)} sub="In delivery" color="#0E7490" />
                        </Grid>
                        <Grid item xs={6} md={3}>
                            <KpiBlock label="Total grant value"     value={fmtMoney(portfolio.totalFunding)} sub="Awarded across all centres" color="#16A34A" />
                        </Grid>
                        <Grid item xs={6} md={3}>
                            <KpiBlock label="Open escalations"      value={fmtNum(totalEsc)} sub="L1 – L5 not yet resolved" color={totalEsc > 0 ? '#DC2626' : '#16A34A'} />
                        </Grid>
                        <Grid item xs={6} md={3}>
                            <KpiBlock label="On-track (Green-RAG)"  value={fmtPct(ragGreenPct)} sub={`${ragData[0].value} of ${ragTotal} active`} color="#16A34A" />
                        </Grid>
                    </Grid>

                    {/* Portfolio RAG donut + Budget vs Actual */}
                    <Grid container spacing={2} sx={{ mb: 4 }} alignItems="flex-start">
                        <Grid item xs={12} md={4}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 1 }}>Portfolio RAG</Typography>
                                <Box sx={{ position: 'relative', height: 220 }}>
                                    <ResponsiveContainer>
                                        <PieChart>
                                            <Pie data={ragData} dataKey="value" innerRadius={62} outerRadius={92} startAngle={90} endAngle={-270} paddingAngle={1}>
                                                {ragData.map((d) => <Cell key={d.name} fill={d.color} />)}
                                            </Pie>
                                            <RTooltip />
                                        </PieChart>
                                    </ResponsiveContainer>
                                    <Box sx={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none' }}>
                                        <Typography variant="h4" sx={{ fontWeight: 800, color: RAG_COLORS.green }}>{ragGreenPct}%</Typography>
                                        <Typography variant="caption" color="text.secondary">on track</Typography>
                                    </Box>
                                </Box>
                                <Stack direction="row" spacing={1} flexWrap="wrap" rowGap={0.5} sx={{ mt: 1, justifyContent: 'center' }}>
                                    {ragData.map((d) => (
                                        <Stack key={d.name} direction="row" spacing={0.5} alignItems="center">
                                            <Box sx={{ width: 8, height: 8, borderRadius: 4, bgcolor: d.color }} />
                                            <Typography variant="caption" color="text.secondary">{d.name} {d.value}</Typography>
                                        </Stack>
                                    ))}
                                </Stack>
                            </Paper>
                        </Grid>
                        <Grid item xs={12} md={8}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 1 }}>Budget vs Actual by Centre (KIMES v5 §9.4)</Typography>
                                <Box sx={{ height: 260 }}>
                                    <ResponsiveContainer>
                                        <BarChart data={fundingByCentre} margin={{ top: 4, right: 16, bottom: 0, left: -16 }}>
                                            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                                            <XAxis dataKey="centre" tick={{ fontSize: 11 }} />
                                            <YAxis tick={{ fontSize: 11 }} />
                                            <RTooltip formatter={(v) => fmtMoney(v)} />
                                            <Bar dataKey="budget" name="Budget" fill="#93c5fd" />
                                            <Bar dataKey="actual" name="Actual" fill="#1d4ed8" />
                                        </BarChart>
                                    </ResponsiveContainer>
                                </Box>
                            </Paper>
                        </Grid>
                    </Grid>

                    {/* ============= SECTION 2: Strategic Plan ============= */}
                    <SectionHeader number={2} title="Strategic Plan progress" blurb={`Mapped to KEMRI's 2023–2027 strategic pillars. Expected Q-share line at ${strategic?.expectedShare ?? '—'}%.`} />
                    <Grid container spacing={2} sx={{ mb: 4 }}>
                        <Grid item xs={12}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Box sx={{ height: 240 }}>
                                    <ResponsiveContainer>
                                        <BarChart
                                            data={strategic?.pillars || []}
                                            layout="vertical"
                                            margin={{ top: 4, right: 32, bottom: 0, left: 0 }}
                                        >
                                            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                                            <XAxis type="number" domain={[0, 100]} tick={{ fontSize: 11 }} unit="%" />
                                            <YAxis dataKey="label" type="category" tick={{ fontSize: 11 }} width={200} />
                                            <RTooltip formatter={(v) => `${v}%`} />
                                            <ReferenceLine x={strategic?.expectedShare || 75} stroke="#dc2626" strokeDasharray="4 4" label={{ value: `Expected ${strategic?.expectedShare || 75}%`, position: 'right', fontSize: 10, fill: '#dc2626' }} />
                                            <Bar dataKey="progressPct" radius={[0, 4, 4, 0]}>
                                                {(strategic?.pillars || []).map((p) => <Cell key={p.key} fill={p.color} />)}
                                            </Bar>
                                        </BarChart>
                                    </ResponsiveContainer>
                                </Box>
                            </Paper>
                        </Grid>
                    </Grid>

                    {/* ============= SECTION 3: Compliance & Governance ============= */}
                    <SectionHeader icon={GavelIcon} number={3} title="Compliance & Governance" blurb="Non-conformity escalation funnel across all centres." />
                    <Grid container spacing={2} sx={{ mb: 4 }} alignItems="flex-start">
                        <Grid item xs={12} md={6}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 1 }}>5-level Escalation Funnel (v5 §9.9)</Typography>
                                <Box sx={{ p: 1 }}>
                                    {escalationFunnel.map((row, i) => {
                                        const maxN = Math.max(...escalationFunnel.map((r) => r.n), 1);
                                        const width = Math.max(25, Math.round((row.n / maxN) * 100));
                                        return (
                                            <Box key={i}
                                                sx={{
                                                    mx: 'auto', my: 0.5, width: `${width}%`,
                                                    bgcolor: row.color, color: 'white',
                                                    px: 1.25, py: 1, borderRadius: 1,
                                                }}>
                                                <Stack direction="row" justifyContent="space-between" alignItems="center">
                                                    <Typography variant="caption" sx={{ fontWeight: 700, color: 'white' }}>{row.stage}</Typography>
                                                    <Chip size="small" label={row.n} sx={{ bgcolor: 'rgba(255,255,255,0.25)', color: 'white', fontWeight: 800, height: 22 }} />
                                                </Stack>
                                            </Box>
                                        );
                                    })}
                                </Box>
                            </Paper>
                        </Grid>
                        <Grid item xs={12} md={6}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 1 }}>SERU watchlist</Typography>
                                <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
                                    Approvals expiring within 60 days, ordered by urgency.
                                </Typography>
                                {(summary?.seruExpiring || []).slice(0, 6).map((s) => (
                                    <Box key={s.projectId} sx={{
                                        display: 'flex', alignItems: 'center', gap: 1, mb: 0.75,
                                        p: 1, borderRadius: 1, border: '1px solid', borderColor: 'divider',
                                    }}>
                                        <Box sx={{
                                            minWidth: 46, textAlign: 'center', py: 0.5, borderRadius: 1,
                                            bgcolor: Number(s.daysToExpiry) <= 14 ? '#fee2e2' : '#fef3c7',
                                            color:   Number(s.daysToExpiry) <= 14 ? '#b91c1c' : '#a16207',
                                        }}>
                                            <Typography variant="h6" sx={{ fontWeight: 800, lineHeight: 1 }}>{s.daysToExpiry}</Typography>
                                            <Typography variant="caption" sx={{ fontSize: 9 }}>days</Typography>
                                        </Box>
                                        <Box sx={{ flex: 1, minWidth: 0 }}>
                                            <Typography variant="body2" sx={{ fontWeight: 600, fontFamily: 'monospace' }} noWrap>{s.kimesProjectId}</Typography>
                                            <Typography variant="caption" color="text.secondary" noWrap sx={{ display: 'block' }}>{s.title}</Typography>
                                        </Box>
                                    </Box>
                                ))}
                                {(summary?.seruExpiring || []).length === 0 && (
                                    <Typography variant="body2" color="text.secondary">All SERU approvals current.</Typography>
                                )}
                            </Paper>
                        </Grid>
                    </Grid>

                    {/* ============= SECTION 4: Items for Board attention ============= */}
                    <SectionHeader icon={WarningIcon} number={4} title="Items requiring Board attention" blurb="DG / Board decisions to consider this quarter." />
                    <Stack spacing={1.25} sx={{ mb: 4 }}>
                        {itemsForBoard.map((it, i) => (
                            <Alert
                                key={i}
                                severity={it.severity === 'critical' ? 'error' : it.severity === 'high' ? 'warning' : it.severity === 'medium' ? 'info' : 'success'}
                            >
                                {it.text}
                            </Alert>
                        ))}
                        <Stack direction="row" spacing={1} flexWrap="wrap" className="kimes-noprint">
                            <Button size="small" component={RouterLink} to={ROUTES.KEMRI_ESCALATIONS} variant="outlined">Open escalation inbox</Button>
                            <Button size="small" component={RouterLink} to={ROUTES.KEMRI_REVIEW_QUEUE} variant="outlined">Open review queue</Button>
                            <Button size="small" component={RouterLink} to={ROUTES.KEMRI_AI_REPORTS} variant="outlined">AI Reports catalog</Button>
                        </Stack>
                    </Stack>

                    {/* ============= SECTION 5: Donor relationship ============= */}
                    <SectionHeader icon={PolicyIcon} number={5} title="Donor relationship summary" blurb="Concurrent reporting status across top funders." />
                    <Grid container spacing={2} sx={{ mb: 4 }}>
                        <Grid item xs={12} md={7}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Typography variant="subtitle2" sx={{ fontWeight: 700, mb: 1 }}>Top funders by study count</Typography>
                                {donorRelationship.length === 0 ? (
                                    <Typography variant="body2" color="text.secondary">No donor data available.</Typography>
                                ) : (
                                    <Stack spacing={0.75}>
                                        {donorRelationship.map((d, i) => (
                                            <Box key={i} sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                                <Typography variant="body2" sx={{ fontWeight: 600, minWidth: 0 }} noWrap>{d.donor}</Typography>
                                                <Box sx={{ flex: 1, height: 6, borderRadius: 3, bgcolor: '#e5e7eb', overflow: 'hidden' }}>
                                                    <Box sx={{
                                                        width: `${Math.min(100, Math.round((d.studies / Math.max(1, donorRelationship[0].studies)) * 100))}%`,
                                                        height: '100%', bgcolor: '#1d4ed8',
                                                    }} />
                                                </Box>
                                                <Typography variant="caption" color="text.secondary" sx={{ minWidth: 80, textAlign: 'right' }}>{d.studies} · {fmtMoney(d.funding)}</Typography>
                                            </Box>
                                        ))}
                                    </Stack>
                                )}
                            </Paper>
                        </Grid>
                        <Grid item xs={12} md={5}>
                            <Paper variant="outlined" sx={{ p: 2, borderRadius: 2 }}>
                                <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}>
                                    <OutputsIcon sx={{ color: '#ef6c00', fontSize: 18 }} />
                                    <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Outputs delivered (cumulative)</Typography>
                                </Stack>
                                <Stack spacing={0.75}>
                                    {outputsByType.length === 0 ? (
                                        <Typography variant="body2" color="text.secondary">No outputs logged yet.</Typography>
                                    ) : outputsByType.map((o) => (
                                        <Stack key={o.outputType} direction="row" justifyContent="space-between">
                                            <Typography variant="body2" sx={{ textTransform: 'capitalize' }}>{String(o.outputType).replace(/_/g, ' ')}</Typography>
                                            <Tooltip title={`avg IF ${o.avgImpact || 0} · ${fmtNum(o.citations || 0)} citations`}>
                                                <Chip size="small" label={o.n} />
                                            </Tooltip>
                                        </Stack>
                                    ))}
                                </Stack>
                            </Paper>
                        </Grid>
                    </Grid>

                    <Divider sx={{ my: 3 }} />
                    <Stack direction={{ xs: 'column', md: 'row' }} spacing={1} justifyContent="space-between" alignItems={{ md: 'center' }} sx={{ opacity: 0.75 }}>
                        <Stack direction="row" spacing={1} alignItems="center">
                            <InsightsIcon sx={{ fontSize: 16, color: '#64748b' }} />
                            <Typography variant="caption" color="text.secondary">
                                Generated by the KIMES AI Reporting Engine · Centre Director / MEL Head review · Director General sign-off required.
                            </Typography>
                        </Stack>
                        <Typography variant="caption" color="text.secondary">
                            Source: KEMRI_KIMES_v5_Final_Complete.pdf §8.3 & §9.
                        </Typography>
                    </Stack>
                </>
            )}
        </Container>
    );
}
